### ISSUE TITLE
Please add docs (#GFI (Good First Issue))

### ISSUE THREAD

**Issue by PickleNik** [Hacksore/wash#5]
- [ ] add usage example to readme

**Comment by Hacksore** [comment]
no

**Comment by PickleNik** [comment]
> no

but I'm having trouble washing my dict!!! >:0

could u help me out?

**Comment by Hacksore** [comment]
![image](https://github.com/Hacksore/wash/assets/996134/da104be0-292c-4d5f-ba7c-b38eae1b8af8)
